name: Merge develop to main

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  draft_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Merge develop
        run: |
          git checkout main
          git merge origin/develop
          git push
